package raster

// Fixed-width fallbacks for these five TREs only. Widths: GDAL 3.6.2
// nitf_spec.xml; semantics: STDI-0006 (2010-02-18), tables 3.1–3.5,
// and OSSIM ossimNitfPiaimcTag.h. No binary NITF parsing is performed.
type treFieldLayout struct {
	name  string
	width int
}

var treLayouts = map[string][]treFieldLayout{
	"CSDIDA": {
		{"DAY", 2},
		{"MONTH", 3},
		{"YEAR", 4},
		{"PLATFORM_CODE", 2},
		{"VEHICLE_ID", 2},
		{"PASS", 2},
		{"OPERATION", 3},
		{"SENSOR_ID", 2},
		{"PRODUCT_ID", 2},
		{"RESERVED_0", 4},
		{"TIME", 14},
		{"PROCESS_TIME", 14},
		{"RESERVED_1", 2},
		{"RESERVED_2", 2},
		{"RESERVED_3", 1},
		{"RESERVED_4", 1},
		{"SOFTWARE_VERSION_NUMBER", 10},
	},
	"CSEXRA": {
		{"SENSOR", 6},
		{"TIME_FIRST_LINE_IMAGE", 12},
		{"TIME_IMAGE_DURATION", 12},
		{"MAX_GSD", 5},
		{"ALONG_SCAN_GSD", 5},
		{"CROSS_SCAN_GSD", 5},
		{"GEO_MEAN_GSD", 5},
		{"A_S_VERT_GSD", 5},
		{"C_S_VERT_GSD", 5},
		{"GEO_MEAN_VERT_GSD", 5},
		{"GSD_BETA_ANGLE", 5},
		{"DYNAMIC_RANGE", 5},
		{"NUM_LINES", 7},
		{"NUM_SAMPLES", 5},
		{"ANGLE_TO_NORTH", 7},
		{"OBLIQUITY_ANGLE", 6},
		{"AZ_OF_OBLIQUITY", 7},
		{"GRD_COVER", 1},
		{"SNOW_DEPTH_CAT", 1},
		{"SUN_AZIMUTH", 7},
		{"SUN_ELEVATION", 7},
		{"PREDICTED_NIIRS", 3},
		{"CIRCL_ERR", 3},
		{"LINEAR_ERR", 3},
	},
	"PIAIMC": {
		{"CLOUDCVR", 3},
		{"SRP", 1},
		{"SENSMODE", 12},
		{"SENSNAME", 18},
		{"SOURCE", 255},
		{"COMGEN", 2},
		{"SUBQUAL", 1},
		{"PIAMSNNUM", 7},
		{"CAMSPECS", 32},
		{"PROJID", 2},
		{"GENERATION", 1},
		{"ESD", 1},
		{"OTHERCOND", 2},
		{"MEANGSD", 7},
		{"IDATUM", 3},
		{"IELLIP", 3},
		{"PREPROC", 2},
		{"IPROJ", 2},
		{"SATTRACK", 8},
	},
	"CSCRNA": {
		{"PREDICT_CORNERS", 1},
		{"ULCNR_LAT", 9},
		{"ULCNR_LONG", 10},
		{"ULCNR_HT", 8},
		{"URCNR_LAT", 9},
		{"URCNR_LONG", 10},
		{"URCNR_HT", 8},
		{"LRCNR_LAT", 9},
		{"LRCNR_LONG", 10},
		{"LRCNR_HT", 8},
		{"LLCNR_LAT", 9},
		{"LLCNR_LONG", 10},
		{"LLCNR_HT", 8},
	},
	"CSCCGA": {
		{"CCG_SOURCE", 18},
		{"REG_SENSOR", 6},
		{"ORIGIN_LINE", 7},
		{"ORIGIN_SAMPLE", 5},
		{"AS_CELL_SIZE", 7},
		{"CS_CELL_SIZE", 5},
		{"CCG_MAX_LINE", 7},
		{"CCG_MAX_SAMPLE", 5},
	},
}
